### ISSUE TITLE
validating speculator

### ISSUE THREAD

**Issue by changhoonhahn** [changhoonhahn/gqp_mc#22]
Comparison between inferred properties using **speculator** versus **FSPS with the same setup** (NMF SFH and ZH bases) reveals some significant discrepancies, especially for log SFR. 

![image](https://user-images.githubusercontent.com/1895640/79787381-beefa500-82fb-11ea-8c01-85970bb125f1.png)

The speculator model call was validated at some point so this is likely not the cause ([see notebook](https://github.com/changhoonhahn/gqp_mc/blob/61f7f566061fa941f06a0e60901d3e065a31afb7/nb/speculator_fsps.ipynb)).

**Comment by changhoonhahn** [comment]
Comparison of the posteriors of the two methods seems to reveal the issue: the FSPS chain has not converged... This is a bit strange because the chains have the same number of iterations and walkers. And the likelihood should be identical, except that FSPS takes >10x the amount of time.

![image](https://user-images.githubusercontent.com/1895640/79787530-0118e680-82fc-11ea-8be8-3adf54c491e9.png)

**Comment by changhoonhahn** [comment]
317e2d0ffb6c00c2227e7f9c06a6da5c8adeddeb : compared `model=speculator` with `model=fsps` for the mini mock challenge ([notebook])(https://github.com/changhoonhahn/gqp_mc/blob/317e2d0ffb6c00c2227e7f9c06a6da5c8adeddeb/nb/baseline_vs_fsps.ipynb)

The comparison revealed a noticeable bias in the inferred stellar mass for `model=speculator`: 
![image](https://user-images.githubusercontent.com/1895640/81742909-a6376280-9455-11ea-9340-94f9a14eae58.png)

**Comment by changhoonhahn** [comment]
I suspect the discrepancy above is due to the python-fsps version issue from Issue #47. @kgb0255 Let's re-do this comparison with the new `model=fsps` runs and check that we get roughly the same posterior for `model=emulator` and `model=fsps`.

**Comment by kgb0255** [comment]
@changhoonhahn Okay. I'll queue emulator chains for the first 10 galaxies.

**Comment by kgb0255** [comment]
@changhoonhahn Hmm, the dust chains haven't finished yet. But for the rest, (emulator, fsps) I got these plots. Black is old and red is new. They look surprisingly similar, but it seems I still need to run append on some chains. I don't suspect my code is outdated as my `fsps` version is 0.3.0 and I git pulled and also ran `setup.py`. 
![emulator_fsps_log1Gyr_old](https://user-images.githubusercontent.com/57269223/90490917-12300380-e0f4-11ea-9ba7-568e48920a17.png)
![emulator_fsps_log1Gyr](https://user-images.githubusercontent.com/57269223/90490918-12c89a00-e0f4-11ea-86ef-985300cb0fa2.png)

**Comment by changhoonhahn** [comment]
Hm, the chains for emulator and fsps seem significantly different even with fsps.

Lets take a step back. Could you try printing out the log posterior for `model=emulator` and `model=fsps` for a set of parameter values within the prior? **We expect the log posterior to be very similar**.

**Comment by changhoonhahn** [comment]
I've compared the SED outputs from`model=emulator` and `model=fsps` over the SFH basis coefficient parameter space in [speculator_accuracy.ipynb](https://github.com/changhoonhahn/gqp_mc/blob/7e66c781395d6bf3095a172cb0af876406c9d819/nb/speculator_accuracy.ipynb). 

It seems the emulator is particularly inaccurate in the region of parameter space occupied by the Dirichlet prior: 
![image](https://user-images.githubusercontent.com/1895640/90712884-fd797a00-e271-11ea-837a-a235206362a3.png). 

Over the larger parameter space the emulator does a better job: 
![image](https://user-images.githubusercontent.com/1895640/90712913-14b86780-e272-11ea-8499-37dc7fa29e26.png)

**Comment by changhoonhahn** [comment]
Closing this issue since this falls under #52
