### ISSUE TITLE
autocorrelation convergence metric

### ISSUE THREAD

**Issue by changhoonhahn** [changhoonhahn/gqp_mc#40]
As I was implementing the max iterations option in the ACM, I realized that Gelman-Rubin might not be the best convergence metric here since we're not using separate chains. Fortunately, I found details on implementing autocorrelation convergence in the `emcee` documentation: https://emcee.readthedocs.io/en/stable/tutorials/autocorr/ 

@kgb0255 Do you think you could implement autocorr in parallel?

**Comment by kgb0255** [comment]
Yes. I'll read through it and implement that.
