### ISSUE TITLE
stationary walkers

### ISSUE THREAD

**Issue by kgb0255** [changhoonhahn/gqp_mc#41]
Chains with scatter 15e-4, 1e-2 included stationary walkers both locally and on NERSC. One possibility is that they are initialized out of prior ranges.

**Comment by changhoonhahn** [comment]
@kgb0255 Is this still an issue or did this go away once we kept the initial walker positions small enough?

**Comment by kgb0255** [comment]
It went away when we kept the positions small enough. I have not checked yet if the underlying reason for that is related to the prior ranges.

**Comment by changhoonhahn** [comment]
I'm not too concerned about this. If you get the chance, take a quick look and we can close out this issue.

**Comment by kgb0255** [comment]
The [stationary walkers](https://github.com/kgb0255/GQPMC_v2_JAMES/blob/0569f0f509c0f3a02d730480bcd43ca8210336e2/Plots/stationary/stationary_prior_beta1_sfh.pdf) were initialized out of the prior ranges.
