### ISSUE TITLE
diagnose iSpeculator 

### ISSUE THREAD

**Issue by changhoonhahn** [changhoonhahn/gqp_mc#48]
There are currently discrepancies between the true galaxy properties and properties inferred from `iSpeculator`. 
![image](https://user-images.githubusercontent.com/1895640/89908716-381d4b80-dbbc-11ea-87ed-27204914351d.png)
The above comparison is for the first 10 LGal galaxies. 

This discrepancy can be caused by the following: 
- bug in the code
- MCMC not converged 
- model limitation (SFH bases, dust)

We need to diagnose the cause of this discrepancy.

**Comment by changhoonhahn** [comment]
The discrepancy in SFRs may also be due to priors on SFR (or SFH) set by the Dirichlet priors.

**Comment by changhoonhahn** [comment]
In this [notebook](https://github.com/changhoonhahn/gqp_mc/blob/570f42da98725476a08a404e7409a1090f89c33e/nb/diagnose_ispeculator.ipynb) I compared the observed photometry and spectroscopy to model(median of posterior) and find good agreement. This suggests that the discrepancy is likely not due to a bug or MCMC convergence issue (this still needs more testing).

**Comment by kgb0255** [comment]
I was able to reproduce the same results in the both notebook with my emulator data

**Comment by changhoonhahn** [comment]
@kgb0255 which results are you referring to?

**Comment by kgb0255** [comment]
@changhoonhahn Sorry for lack of clarity. I sshed to NERSC to access my data and was able to reproduce the same output in both notebooks - sfh_basis_transform, diagnose_ispeculator.ipynb.

**Comment by changhoonhahn** [comment]
Closing this issue since this falls under #52
